### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by YangLinger** [LarryUESTC/GRLC#1]
Hello, I would like to ask if we need to download the data set of this code ourselves? If so, how to configure the corresponding data set address after downloading? I reported an error when there was no configuration: FileNotFoundError: [Errno 2] No such file or directory 'log'.

**Comment by LarryUESTC** [comment]
Thanks for your feedback. 
Can you provide more information, such as the specific code line causing the error? Based on your description, it seems that the error might be occurring during the data preprocessing stage. There are two possible reasons for this: either the data was not successfully loaded, or there is a compatibility issue between the preprocessing code and the current version of the library.
Lastly, you mentioned that the data downloading and preprocessing were done using a library based on the previous method. Specifically, you can refer to the torch_geometric library for more details on downloading and preprocessing the data.

**Comment by YangLinger** [comment]
thank you for your reply.
My problem code line is the filename of 584 in train.py, but this is because the filePath="log" in line 582 means that there is no “log” file. So I want to ask, this code will be automatically downloaded through the torch-geometric library, right?

**Comment by LarryUESTC** [comment]
I see. Don't worry, these codes (lines 579-588) are used to record
experimental results and can be deleted, also replacing 'exp_name' with
whatever you want. The error is occurring because the relevant folders have
not been created.
If you want to record experimental results, I suggest using the Wandb
library.

YangLinger ***@***.***> 于2023年10月27日周五 11:23写道：

**Comment by YangLinger** [comment]
Thank you for your help, the code is now running normally.
