### ISSUE TITLE
使用GAT的正确率不对？

### ISSUE THREAD

**Issue by YangLinger** [LarryUESTC/GRLC#2]
作者您好，我用GAT跑出来正确率只有13%，麻烦您帮忙看看哪里出了问题。
![QQ截图20231212200353](https://github.com/LarryUESTC/GRLC/assets/87008602/aaa24b37-2b61-4762-816c-e5cd7fc40759)
![QQ截图20231212200525](https://github.com/LarryUESTC/GRLC/assets/87008602/ce532d26-0928-40c7-afa4-bf0b54c0a80f)

**Comment by LarryUESTC** [comment]
I apologize for the delayed response. 
I have been quite busy recently, but I will make it a priority to review your question as soon as possible.

**Comment by LarryUESTC** [comment]
From the graph, it appears that your loss hasn't significantly decreased. However, this is unlikely to be the main reason for such a low accuracy. There might be a bug somewhere in the codes. 
I suggest conducting a step-by-step debug check to identify the issue.

**Comment by YangLinger** [comment]
Ok, thank you for your advice.
